### ISSUE TITLE
Issue with building parts

### ISSUE THREAD

**Issue by champ2410** [laurent-martin/ets-to-homeassistant#12]
Hello, thank you for the project! It is very useful.

I am running ETS5.5 and I tried to create building functions as you described but unfortunately, there are no recognized why the script. The following message is displayed: "No builing information".

Digging into the details, it seems like my ETS file does not have a "Location" node within the "Installation" node but instead, a "BuildingPart".

I am not 100% sure if we don't have the same version of ETS or if I am not extracting my project correctly, but please help.

Many thanks,
Guillaume

**Comment by champ2410** [comment]
Also I noticed that the function types are like "DimmableLight" in my files, but "dimmable_light" in the script. So seems like a version issue of some sort...

**Comment by laurent-martin** [comment]
Thans for reporting that.

I fix the code so that it also accepts Buildings/BuildingPart in addition to Locations/Space

Concerning dimmable_light in the script, it's only an internal identifier mapping function type , e.g. FT-2 to readable identifier, e.g. dimmable_light
Then later this identier is used to generate the knx type in home assistant

**Comment by laurent-martin** [comment]
@champ2410 : did you test the new version ?

**Comment by champ2410** [comment]
@laurent-martin Sorry for the delay! This fixed it!
